services:
  anx-calibre-manager:
    image: ghcr.io/ptbsare/anx-calibre-manager:latest
    volumes:
      - config:/config
      - webdav:/webdav
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      GUNICORN_WORKERS: 2
      SECRET_KEY: ${SERVICE_REALBASE64_64_CALIBRE}
      CALIBRE_URL: ${CALIBRE_URL:?}
      CALIBRE_USERNAME: ${CALIBRE_USERNAME:?}
      CALIBRE_PASSWORD: ${CALIBRE_PASSWORD:?}
      CALIBRE_DEFAULT_LIBRARY_ID: Calibre_Library
      CALIBRE_ADD_DUPLICATES: false

volumes:
  config:
  webdav:
